extern   double    CONSTANTS[20][2];
extern   double    PFACTOR[3][7];
extern int read_file(char*, ior_rec_t*);
extern void calc_hull(ior_rec_t *u, calc_rec_t *c);
extern double trunc_to(double value, int decp);
extern void calc_rmc(ior_rec_t *u, calc_rec_t *c) ;
extern void calc_prop(ior_rec_t *u, calc_rec_t *c);
extern void calc_prop(ior_rec_t *u, calc_rec_t *c);
extern void calc_rig(ior_rec_t *u, calc_rec_t *c);
extern void calc_rtg(ior_rec_t *u, calc_rec_t *c);
extern void show_rtg(ior_rec_t *u, calc_rec_t *c);
extern void ior_cert(char *fp, ior_rec_t*, calc_rec_t*,  char *[][2], int *);
extern void pcert(ior_rec_t *u, calc_rec_t *c);
